In [36]:
from setting import Settings
import numpy as np

In [37]:
angle_degrees = 60
angle_radians = np.radians(angle_degrees)

rotation_matrix = np.array([
    [np.cos(angle_radians), -np.sin(angle_radians), 0, 0],
    [np.sin(angle_radians),  np.cos(angle_radians), 0, 0],
    [0, 0, 1, 0],
    [0, 0, 0, 1]
])

In [41]:
settings = Settings()
c2w = np.array(settings.camera_poses['camera_path'][0]['camera_to_world']).reshape(4, 4)

In [44]:
print(settings.camera_poses['camera_path'][3]['camera_to_world'])

[[0.10231189425704014], [0.48911119307539097], [0.8662000445058311], [0.5058938174837787], [-0.9947523693329592], [0.050305879341026004], [0.08909007919061408], [0.0003705601201718159], [5.81053666504635e-16], [-0.8707695213499914], [0.4916914079866622], [0.3994575663738732], [0.0], [0.0], [0.0], [1.0]]


In [40]:
for i in range(1, len(settings.camera_poses['camera_path'])):
   c2w = c2w @ rotation_matrix
   # print(c2w)
   c2w_new = c2w.reshape(16, 1)
   settings.camera_poses['camera_path'][i]['camera_to_world'] = c2w_new.tolist()
   print(c2w_new.tolist())

[[-0.4747386656071242], [-0.15595089700179138], [0.8662000445058311], [0.5058938174837787], [0.4538100151974361], [-0.8866337619876163], [0.08909007919061408], [0.0003705601201718159], [0.7541085263303087], [0.43538476067499604], [0.4916914079866622], [0.3994575663738732], [0.0], [0.0], [0.0], [1.0]]
[[-0.3724267713500839], [0.33316029607359954], [0.8662000445058311], [0.5058938174837787], [-0.540942354135523], [-0.83632788264659], [0.08909007919061408], [0.0003705601201718159], [0.754108526330309], [-0.43538476067499543], [0.4916914079866622], [0.3994575663738732], [0.0], [0.0], [0.0], [1.0]]
[[0.10231189425704014], [0.48911119307539097], [0.8662000445058311], [0.5058938174837787], [-0.9947523693329592], [0.050305879341026004], [0.08909007919061408], [0.0003705601201718159], [5.81053666504635e-16], [-0.8707695213499914], [0.4916914079866622], [0.3994575663738732], [0.0], [0.0], [0.0], [1.0]]
[[0.474738665607124], [0.15595089700179157], [0.8662000445058311], [0.5058938174837787], [-0.4

In [35]:
settings.camera_poses['camera_path']

[{'camera_to_world': [-0.10231189425704039,
   -0.489111193075391,
   0.8662000445058311,
   0.5058938174837787,
   0.9947523693329594,
   -0.05030587934102655,
   0.08909007919061408,
   0.0003705601201718159,
   -1.5265566588595905e-16,
   0.8707695213499916,
   0.4916914079866622,
   0.3994575663738732,
   0,
   0,
   0,
   1],
  'fov': 60,
  'aspect': 1},
 {'camera_to_world': [[-0.4747386656071242],
   [-0.15595089700179138],
   [0.8662000445058311],
   [0.5058938174837787],
   [0.4538100151974361],
   [-0.8866337619876163],
   [0.08909007919061408],
   [0.0003705601201718159],
   [0.7541085263303087],
   [0.43538476067499604],
   [0.4916914079866622],
   [0.3994575663738732],
   [0.0],
   [0.0],
   [0.0],
   [1.0]],
  'fov': 60,
  'aspect': 1},
 {'camera_to_world': [[-0.3724267713500839],
   [0.33316029607359954],
   [0.8662000445058311],
   [0.5058938174837787],
   [-0.540942354135523],
   [-0.83632788264659],
   [0.08909007919061408],
   [0.0003705601201718159],
   [0.7541085263

In [23]:
import os

# Replace 'your_directory_path' with the actual path to the directory
directory_path = r'/workspace/inthewild/bigexample/Apr7at4-46PM-poly/keyframes/corrected_cameras'

# List all files in the directory
all_files = [f for f in os.listdir(directory_path) if os.path.isfile(os.path.join(directory_path, f))]

# Sort the files alphabetically
all_files.sort()

# Get the first file in the sorted list
first_file = all_files[0] if all_files else None

# Print the first file
print(first_file)

1915868460001.json


In [32]:
import json

file_path = directory_path + '/' + first_file
# Replace 'file_path.json' with the actual path to your JSON file
with open(file_path, 'r') as file:
    data = json.load(file)

# Now, 'data' contains the contents of the JSON file as a Python dictionary
print(data)

{'blur_score': 177.5570526123047, 'cx': 514.4260864257812, 'cy': 383.7248229980469, 'fx': 770.0746239830255, 'fy': 770.0746239830255, 'height': 768, 'manual_keyframe': False, 'neighbors': [1915954985708, 1916188352730, 1916189386359, 1915954518908, 1916187685869, 1915955719258, 1915871844385, 1915874045070, 1915874195115, 1915913340180], 't_00': -0.032949190586805344, 't_01': 0.9902731776237488, 't_02': -0.13517914712429047, 't_03': -0.09575456380844116, 't_10': -0.9475382566452026, 't_11': 0.012074971571564674, 't_12': 0.3194141983985901, 't_13': -0.0339953750371933, 't_20': 0.3179395794868469, 't_21': 0.13861185312271118, 't_22': 0.9379238486289978, 't_23': 0.2467084676027298, 'timestamp': 1915868460001, 'width': 1024}


In [46]:
import numpy as np

camera_to_world_matrix = np.zeros((4, 4))

prefix = 't_'

for i in range(3):
    for j in range(4):
      # print(prefix + str(i) + str(j))
      # print(data[prefix + str(i) + str(j)])
      camera_to_world_matrix[i][j] = data[prefix + str(i) + str(j)]

camera_to_world_matrix[2][1] = 0
camera_to_world_matrix[3][3] = 1

In [47]:
print(camera_to_world_matrix)

[[-0.03294919  0.99027318 -0.13517915 -0.09575456]
 [-0.94753826  0.01207497  0.3194142  -0.03399538]
 [ 0.31793958  0.          0.93792385  0.24670847]
 [ 0.          0.          0.          1.        ]]


In [34]:
from nerf_grounding_chat_interface.chat.model_context import ModelContextManager

In [14]:
modelcontext = ModelContextManager.get_model_context()

load_config:  /workspace/inthewild/outputs/bigexample/lerf/2023-04-22_022439/config.yml
output_path:  /workspace/nerf-grounding-chat-interface/grounder_images/results
Initialize Blip2Captioner
[2023-05-09 06:46:48,449] INFO root [__init__] [blip2_t5.py:69] - freeze vision encoder


Loading checkpoint shards:   0%|          | 0/5 [00:00<?, ?it/s]

[2023-05-09 06:48:32,006] INFO root [load_from_pretrained] [blip2.py:96] - load checkpoint from https://storage.googleapis.com/sfr-vision-language-research/LAVIS/models/BLIP2/blip2_pretrained_flant5xxl.pth
Initialize LERF pipeline
[2023-05-09 06:48:37,892] INFO torch.distributed.nn.jit.instantiator [<module>] [instantiator.py:21] - Created a temporary directory at /tmp/tmpvfhanimd
[2023-05-09 06:48:37,894] INFO torch.distributed.nn.jit.instantiator [_write] [instantiator.py:76] - Writing /tmp/tmpvfhanimd/_remote_module_non_scriptable.py
[2023-05-09 06:48:38,263] INFO root [create_model] [factory.py:158] - Loaded ViT-B-16 model config.
[2023-05-09 06:48:39,443] INFO root [create_model] [factory.py:206] - Loading pretrained ViT-B-16 weights (laion2b_s34b_b88k).


[06:48:41] Auto image downscale factor of 1                                                 ]8;id=830414;file:///workspace/nerfstudio/nerfstudio/data/dataparsers/nerfstudio_dataparser.py\nerfstudio_dataparser.py]8;;\:]8;id=137489;file:///workspace/nerfstudio/nerfstudio/data/dataparsers/nerfstudio_dataparser.py#339\339]8;;\

           Skipping 0 files in dataset split train.                                         ]8;id=627656;file:///workspace/nerfstudio/nerfstudio/data/dataparsers/nerfstudio_dataparser.py\nerfstudio_dataparser.py]8;;\:]8;id=921739;file:///workspace/nerfstudio/nerfstudio/data/dataparsers/nerfstudio_dataparser.py#167\167]8;;\

            Dataset is overriding orientation method to none                                ]8;id=975027;file:///workspace/nerfstudio/nerfstudio/data/dataparsers/nerfstudio_dataparser.py\nerfstudio_dataparser.py]8;;\:]8;id=845071;file:///workspace/nerfstudio/nerfstudio/data/dataparsers/nerfstudio_dataparser.py#220\220]8;;\

           Skipping 0 files in dataset split test.                                          ]8;id=498952;file:///workspace/nerfstudio/nerfstudio/data/dataparsers/nerfstudio_dataparser.py\nerfstudio_dataparser.py]8;;\:]8;id=914672;file:///workspace/nerfstudio/nerfstudio/data/dataparsers/nerfstudio_dataparser.py#167\167]8;;\

            Dataset is overriding orientation method to none                                ]8;id=66036;file:///workspace/nerfstudio/nerfstudio/data/dataparsers/nerfstudio_dataparser.py\nerfstudio_dataparser.py]8;;\:]8;id=879310;file:///workspace/nerfstudio/nerfstudio/data/dataparsers/nerfstudio_dataparser.py#220\220]8;;\

Setting up training dataset...

Caching all 488 images.

Output()

Setting up evaluation dataset...

Caching all 4 images.

Output()

Scales: 100%|██████████| 7/7 [00:00<00:00, 17.61it/s]


Loading latest checkpoint from load_dir

✅ Done loading checkpoint from 
/workspace/inthewild/outputs/bigexample/lerf/2023-04-22_022439/nerfstudio_models/step-000020000.ckpt

Initialize visualGrounder


In [48]:
from settings import Settings

settings = Settings()

camera_pose_preset = settings.camera_poses 

In [49]:
angle_degrees = 60
angle_radians = np.radians(angle_degrees)
rotation_matrix_x = np.array([
    [1, 0, 0, 0],
    [0, np.cos(angle_radians), -np.sin(angle_radians), 0],
    [0, np.sin(angle_radians), np.cos(angle_radians), 0],
    [0, 0, 0, 1]
])

rotation_matrix_y = np.array([
    [np.cos(angle_radians), 0, np.sin(angle_radians), 0],
    [0, 1, 0, 0],
    [-np.sin(angle_radians), 0, np.cos(angle_radians), 0],
    [0, 0, 0, 1]
])

rotation_matrix_z = np.array([
    [np.cos(angle_radians), -np.sin(angle_radians), 0, 0],
    [np.sin(angle_radians), np.cos(angle_radians), 0, 0],
    [0, 0, 1, 0],
    [0, 0, 0, 1]
])

c2w = camera_to_world_matrix
c2w_new = c2w.reshape(16, 1)
settings.camera_poses['camera_path'][0]['camera_to_world'] = c2w_new.tolist()
for i in range(1, len(settings.camera_poses['camera_path'])):
   c2w = c2w @ rotation_matrix_z
   c2w_new = c2w.reshape(16, 1)
   settings.camera_poses['camera_path'][i]['camera_to_world'] = c2w_new.tolist()

In [50]:
modelcontext.visualGrounder.camera_poses = settings.camera_poses

In [51]:
modelcontext.visualGrounder.taking_pictures()

picture taking process
sub picture taking process


Taking 6 images... 

Finish taking 6 images... 

[ImageRef(id=0, clip_address='/workspace/nerf-grounding-chat-interface/grounder_images/clip/000.png', rgb_address='/workspace/nerf-grounding-chat-interface/grounder_images/rgb/000.png', encoding=array([[[0.39593184, 0.39593184, 0.39593184],
         [0.3946856 , 0.3946856 , 0.3946856 ],
         [0.39199623, 0.39199623, 0.39199623],
         ...,
         [0.4752297 , 0.4752297 , 0.4752297 ],
         [0.47621298, 0.47621298, 0.47621298],
         [0.47359684, 0.47359684, 0.47359684]],
 
        [[0.39046374, 0.39046374, 0.39046374],
         [0.38996115, 0.38996115, 0.38996115],
         [0.38926718, 0.38926718, 0.38926718],
         ...,
         [0.47423404, 0.47423404, 0.47423404],
         [0.47625548, 0.47625548, 0.47625548],
         [0.47304374, 0.47304374, 0.47304374]],
 
        [[0.38866764, 0.38866764, 0.38866764],
         [0.38714254, 0.38714254, 0.38714254],
         [0.38596532, 0.38596532, 0.38596532],
         ...,
         [0.4720834 , 0.4720834 , 0.4720834 ],
      